version: "3.8"
services:
  backend:
    build: ./backend
    container_name: arbitrage-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: nginx:alpine
    container_name: arbitrage-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: always
    environment:
      - API_URL=http://backend:8000
